name: Test

on: [push]

jobs:
  testsolaris:
    runs-on: macos-latest
    name: Test a cf tunnel
    steps:
    - uses: actions/checkout@v3
    - name: Run establish a cf tunnel
      id: test
      uses: vmactions/cf-tunnel@main
      with:
        protocol: tcp
        port: 22
    - name: sleep
      run: sleep 30
